// AUTO-GENERATED by scripts/set-env.js — do not edit by hand.
export const environment = {
  production: false,
  firebase: {
    apiKey: 'AIzaSyDTCrPYCVocr4Q-BcObT4WrgN1milXtM8U',
    authDomain: 'personal-reading-list-b96cd.firebaseapp.com',
    projectId: 'personal-reading-list-b96cd',
    storageBucket: 'personal-reading-list-b96cd.firebasestorage.app',
    messagingSenderId: '435668411100',
    appId: '1:435668411100:web:a8e643df05424b29ef4a19',
  },
  openLibraryBaseUrl: 'https://openlibrary.org',
  openLibraryCoversUrl: 'https://covers.openlibrary.org',
};
