// @ts-check
'use strict';

/**
 * Reads Firebase config from .env and writes Angular environment files.
 * Run via `npm run env:setup` or automatically via prestart / prebuild.
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

const missing = required.filter(key => !process.env[key] || process.env[key].startsWith('your-'));
if (missing.length > 0) {
  console.error('\n❌  Missing or unfilled Firebase config in .env:');
  missing.forEach(k => console.error(`   • ${k}`));
  console.error('\n   Copy .env.example → .env and fill in your Firebase values.\n');
  process.exit(1);
}

const firebase = `{
    apiKey: '${process.env['FIREBASE_API_KEY']}',
    authDomain: '${process.env['FIREBASE_AUTH_DOMAIN']}',
    projectId: '${process.env['FIREBASE_PROJECT_ID']}',
    storageBucket: '${process.env['FIREBASE_STORAGE_BUCKET']}',
    messagingSenderId: '${process.env['FIREBASE_MESSAGING_SENDER_ID']}',
    appId: '${process.env['FIREBASE_APP_ID']}',
  }`;

const devEnv = `// AUTO-GENERATED by scripts/set-env.js — do not edit by hand.
export const environment = {
  production: false,
  firebase: ${firebase},
  openLibraryBaseUrl: 'https://openlibrary.org',
  openLibraryCoversUrl: 'https://covers.openlibrary.org',
};
`;

const prodEnv = `// AUTO-GENERATED by scripts/set-env.js — do not edit by hand.
export const environment = {
  production: true,
  firebase: ${firebase},
  openLibraryBaseUrl: 'https://openlibrary.org',
  openLibraryCoversUrl: 'https://covers.openlibrary.org',
};
`;

const envDir = path.resolve(__dirname, '../src/environments');
fs.writeFileSync(path.join(envDir, 'environment.ts'), devEnv);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), prodEnv);

console.log('✅  Environment files generated from .env');
